#!/bin/bash
# Copyright (C) 2016 by SUSE LINUX GmbH.
# Author: Fabian Vogt <fvogt@suse.com>, 2016.
# This program is under GPL license. See COPYING file for details.

DEFAULT_CATALOG="/etc/xml/catalog-d.xml"
DEFAULT_GENDIR="/etc/xml/catalog.d"
SKIPVALID=

# Print help or version
case $1 in
    --skipvalid)
      SKIPVALID=1
      shift
    ;;
    --version)
      echo "update-xml-catalog 0.6 (part of sgml-skel)"
      exit 0
    ;;
    -h|--help)
      echo -e "update-xml-catalog 0.6 (part of sgml-skel)\n\
\n\
Generates ${DEFAULT_CATALOG} from the files in ${DEFAULT_GENDIR}\n\
The output file can be overwritten by setting the first parameter,\n\
the input directory as second parameter. Examples:\n\
\n\
update-xml-catalog /tmp/tmpcatalog.xml\n\
update-xml-catalog /tmp/tmpcatalog.xml /tmp/tmpcatalog.d"
      exit 0
    ;;
    --)
      shift
    ;;
esac

CATALOG=${1:-$DEFAULT_CATALOG}
GENDIR=${2:-$DEFAULT_GENDIR}

# die: Echo arguments to stderr and exit with 1
die() { echo "$@" 1>&2 ; exit 1; }

# Basic checks
[ -w "$CATALOG" ] || [ -w "$(dirname -- "$CATALOG")" ] || die "No permission to write catalog"
[ -d "$GENDIR" ] || die "Source directory does not exist"

# Create temporary file
tmpfile=$(mktemp) || die "Could not create temporary file"
# Remove it on exit
trap rm\ -f\ "$tmpfile" EXIT

# Write catalog header
cat > "$tmpfile" <<EOF
<?xml version="1.0"?>
<!DOCTYPE catalog PUBLIC "-//OASIS//DTD Entity Resolution XML Catalog V1.0//EN" "http://www.oasis-open.org/committees/entity/release/1.0/catalog.dtd">
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
<!-- Bogus entry to avoid this being empty -->
<uri name="http://this.does/not#exist" uri="file:///does/not/exist/either"/>
EOF

[ $? -eq 0 ] || die "cat failed"

# Write the catalog entries:
# List all non-hidden files in GENDIR recursively, sort the paths and pass them to xsltproc
# The XSL source is passed as fifo.

find "$(realpath -- "$GENDIR")" -type f -name "[!.]*" -print0 | sort -z | xargs -0 xsltproc >> "$tmpfile" <(
cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="xml" indent="no" omit-xml-declaration="yes"/>
  <xsl:template match="/*">
    <xsl:copy-of select="node()"/>
  </xsl:template>
</xsl:stylesheet>
EOF
) || die "xsltproc failed"

# Write the catalog footer
echo "</catalog>" >> "$tmpfile" || die "echo failed"

# If validation skipped or RNG schema does not exist, skip validation
if [ -z "$SKIPVALID" ] && [ -f "/usr/share/xml/xmlcatalog/schema/rng/catalog.rng" ]; then
  if ! err=$(xmllint --noout --relaxng  "/usr/share/xml/xmlcatalog/schema/rng/catalog.rng" "$tmpfile" 2>&1); then
    echo $err >&2
    die "Generated catalog not valid"
  fi
fi

# Finally rename
mv -- "$tmpfile" "$CATALOG" || die "mv failed"
